In [1]:
import pandas as pd

In [2]:
train_data_path = 'train_data.csv'
train_label_path = 'train_labels.csv'

In [3]:
train_label = pd.read_csv(train_label_path)

In [4]:
train_label.head(2)

                                         customer_ID  target
0  0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...       0
1  00000fd6641609c6ece5454664794f0340ad84dddce9a2...       0

In [5]:
train_data = [elem for elem in pd.read_csv(train_data_path,chunksize=100000)][0]

In [6]:
train_data

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,049dd5e7b5a6895c4f8b179362d8e91f26ebf0b6c95e99...,2018-01-02,0.458911,0.124405,0.597829,0.023698,0.004703,0.162860,0.000963,0.627714,...,NaN,NaN,NaN,0.004281,0.003969,0.003936,NaN,0.006478,0.003046,0.004138
99996,049dd5e7b5a6895c4f8b179362d8e91f26ebf0b6c95e99...,2018-02-27,0.363298,0.038383,0.675999,0.023201,0.006627,0.160133,0.000720,0.822903,...,NaN,NaN,NaN,0.004239,0.008563,0.003117,NaN,0.006679,0.007450,0.002982
99997,049dd5e7b5a6895c4f8b179362d8e91f26ebf0b6c95e99...,2018-03-08,0.356621,0.036849,0.645728,0.020585,0.004587,0.166246,0.003972,0.871214,...,NaN,NaN,NaN,0.009920,0.005579,0.008481,NaN,0.001516,0.005997,0.004767
99998,049e0948e285ec6767bf07e6e3f5e0919821ee200e359d...,2017-03-29,0.714477,0.000546,0.008019,0.817670,0.006265,NaN,0.008652,0.008341,...,NaN,NaN,NaN,1.006665,0.003085,0.914985,0.351957,1.001686,0.579711,0.454960
99999,049e0948e285ec6767bf07e6e3f5e0919821ee200e359d...,2017-04-28,0.614861,0.008513,0.008796,0.813174,0.008680,NaN,0.002812,0.009391,...,NaN,NaN,NaN,1.006981,0.003211,0.914737,0.356866,1.001302,0.669118,0.460121